version: '2.1'

services:
  e-commerce:
    build: .
    volumes:
      - /data/e-commerce
    depends_on:
      docker-mysql:
        condition: service_healthy
    ports:
      - 8080:8080

  docker-mysql:
    image: mysql
    environment:
      - MYSQL_DATABASE=sys
      - MYSQL_PASSWORD=Root123
      - MYSQL_ROOT_PASSWORD=Root123
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10